alter table if exists public.movie_oshi rename to list_movie;

create table if not exists public.list (
  list_id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid(),
  favorite_count integer not null default 0,
  can_display boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.list enable row level security;
alter table public.list_movie enable row level security;

drop policy if exists "User read" on public.list_movie;
drop policy if exists "User insert" on public.list_movie;
drop policy if exists "User delete" on public.list_movie;

insert into public.list (user_id)
select distinct user_id
from public.list_movie
on conflict do nothing;

alter table public.list_movie add column if not exists list_id bigint;

update public.list_movie
set list_id = list.list_id
from public.list
where list.user_id = list_movie.user_id;

alter table public.list_movie drop constraint if exists episode_oshi_pkey;
alter table public.list_movie drop constraint if exists movie_oshi_pkey;
alter table public.list_movie drop constraint if exists list_movie_pkey;
alter table public.list_movie add primary key (list_id, movie_id);

alter table public.list_movie
  add constraint list_movie_list_id_fkey
  foreign key (list_id)
  references public.list(list_id)
  on delete cascade;

alter table public.list_movie
  drop column if exists user_id;

alter table public.list_movie
  alter column list_id set not null;

-- list policies

drop policy if exists "List owner read" on public.list;
create policy "List owner read" on public.list
for select
to authenticated
using (user_id = auth.uid() or can_display = true);

drop policy if exists "List owner insert" on public.list;
create policy "List owner insert" on public.list
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "List owner update" on public.list;
create policy "List owner update" on public.list
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "List owner delete" on public.list;
create policy "List owner delete" on public.list
for delete
to authenticated
using (user_id = auth.uid());

-- list_movie policies

drop policy if exists "List movie read" on public.list_movie;
create policy "List movie read" on public.list_movie
for select
to authenticated
using (
  exists (
    select 1
    from public.list
    where list.list_id = list_movie.list_id
      and (list.user_id = auth.uid() or list.can_display = true)
  )
);

drop policy if exists "List movie write" on public.list_movie;
create policy "List movie write" on public.list_movie
for insert
to authenticated
with check (
  exists (
    select 1
    from public.list
    where list.list_id = list_movie.list_id
      and list.user_id = auth.uid()
  )
);

drop policy if exists "List movie delete" on public.list_movie;
create policy "List movie delete" on public.list_movie
for delete
to authenticated
using (
  exists (
    select 1
    from public.list
    where list.list_id = list_movie.list_id
      and list.user_id = auth.uid()
  )
);

grant select, insert, update, delete on table public.list to authenticated;
grant select, insert, delete on table public.list_movie to authenticated;
