begin;

-- 1) history_id を identity に
alter table public.history
  alter column history_id add generated by default as identity;

-- 2) 型変換（既存データがUUID文字列である前提）
alter table public.history
  alter column user_id type uuid using user_id::uuid;

alter table public.history
  alter column movie_id type uuid using movie_id::uuid;

-- 3) RLSポリシー整理
alter table public.history enable row level security;

drop policy if exists "Public read" on public.history;
drop policy if exists "History read" on public.history;
drop policy if exists "History insert" on public.history;

create policy "History read" on public.history
for select
to authenticated
using (user_id = auth.uid());

create policy "History insert" on public.history
for insert
to authenticated
with check (user_id = auth.uid());

-- 4) 権限
revoke all on table public.history from anon;
grant select, insert on table public.history to authenticated;

commit;
